language: java
jdk:
  - openjdk7
  - openjdk6
  - openjdk8
  - openjdk10
  - openjdk11

# Workaround for buffer overflow with openjdk6
# https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hosts:
    - myshorthost
  hostname: myshorthost

after_success:
  - bash <(curl -s https://codecov.io/bash)
